package ten40EZ;
//DO NOT Edit this file  ******************************
public interface EZ1040Methods{
  int getLine1(String prompt);
  int getLine2(String prompt);
  int getLine3(String prompt);
  int calculateLine4(int line1, int line2, int line3);
  int getLine5A(String prompt);  // returns 0 if you are NOT a dependent, 1 if you are a dependent
  int calculateLine5(int line1, int line5A);
  int calculateLine6(int line4, int line5);
  int getLine7(String prompt);
  //line 8a = 0
  int calculateLine9(int line7, int line8);
  int getLine10(String prompt, int line6);
  //line 11 = 0;
  int calculateLine12(int line10, int line11);
  int calculateLine13(int line9, int line12);
  int calculateLine14(int line9, int line12);  
}
//DO NOT Edit this file  *****************************